use serde_json::{Value, json};

use crate::ops;

#[must_use]
pub fn feature_catalog() -> Value {
    let rows = vec![
        supported(
            "scene.graph",
            "Scene and View Layer",
            "Scene",
            &["scene.create", "scene.update"],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "collection.graph",
            "Collection hierarchy, membership, instances, and view-layer exclusions",
            "Collection",
            &[
                "collection.create",
                "collection.instance_create",
                "collection.update",
                "collection.link",
                "collection.parent",
                "collection.unlink",
            ],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "object.mesh_primitive",
            "Mesh primitive objects",
            "Mesh Object",
            &["node.create"],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "object.transform",
            "Object transforms and parenting",
            "Object",
            &["node.update", "node.parent"],
            [false, true, true, true, false, false, false],
        ),
        supported(
            "object.duplicate_delete",
            "Object duplication and deletion",
            "Object",
            &["node.duplicate", "node.delete"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "object.mesh_join",
            "Join mesh objects into the active mesh",
            "Object",
            &["node.join"],
            [false, true, true, true, false, false, false],
        ),
        supported(
            "data.single_user",
            "Make data single-user",
            "Data-Block",
            &["data.make_single_user"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "material.simple_pbr",
            "Base color, metallic, roughness, emission, transmission, IOR, texture maps, and alpha modes",
            "Material",
            &["material.create", "material.update"],
            [true, true, true, true, true, true, false],
        ),
        supported(
            "shader.evaluator_subset",
            "Principled, procedural surface nodes, and PBR texture maps",
            "ShaderNodeTree",
            &["material.create"],
            [true, false, true, true, false, false, false],
        ),
        unsupported(
            "shader.advanced",
            "Other Blender shader nodes",
            "ShaderNodeTree",
            &[],
            "Shader nodes outside the native surface, volume, displacement, and world evaluator subsets are not supported.",
        ),
        supported(
            "shader.output_material.volume",
            "Output Material volume surface with analytic extinction and scattering",
            "ShaderNodeOutputMaterial",
            &[
                "graph.create",
                "graph.node_add",
                "graph.link",
                "material.create",
                "material.update",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "render.volume.scattering",
            "Density-weighted Henyey-Greenstein scattering, direct lighting, environment illumination, and volume emission",
            "Volume",
            &[
                "volume.create",
                "volume.update",
                "material.create",
                "material.update",
                "graph.create",
                "graph.node_add",
                "graph.link",
            ],
            [false, true, true, true, true, false, false],
        ),
        supported(
            "shader.output_material.displacement",
            "Output Material displacement with bump shading and subdivided true displacement",
            "ShaderNodeOutputMaterial",
            &[
                "graph.create",
                "graph.node_add",
                "graph.link",
                "material.create",
                "material.update",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "mesh.polygon_topology",
            "Persistent polygon mesh topology",
            "Mesh",
            &["node.create"],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "metaball.implicit_surface",
            "Signed metaball elements polygonized into a mesh surface",
            "Metaball",
            &["metaball.create", "metaball.update"],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "lattice.control_cage",
            "Regular lattice cages with weighted mesh deformation",
            "Lattice",
            &[
                "lattice.create",
                "lattice.update",
                "modifier.create",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "pointcloud.points",
            "Persistent point IDs and point-domain attributes rendered as loose points",
            "PointCloud",
            &["pointcloud.create", "pointcloud.update"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "volume.inline_grids",
            "Inline or little-endian blob f32 grids, trilinear density sampling, and mesh conversion",
            "Volume",
            &[
                "volume.create",
                "volume.update",
                "modifier.create",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "volume.openvdb_evaluation",
            "Read-only OpenVDB sampling, active bounds, and density mesh conversion for Blender float and vec3s 5-4-3 trees",
            "Volume",
            &[
                "volume.create",
                "volume.update",
                "modifier.create",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "volume.openvdb_evaluation.file_version",
            "OpenVDB archives outside the supported file-version range",
            "Volume",
            &["volume.create", "volume.update"],
            "Only OpenVDB file versions 222 through 225 are decoded.",
        ),
        unsupported(
            "volume.openvdb_evaluation.transform",
            "Nonlinear and compound OpenVDB transforms",
            "Volume",
            &["volume.create", "volume.update"],
            "Uniform scale, scale, translation, scale-translation, and affine maps are supported.",
        ),
        unsupported(
            "volume.openvdb_evaluation.value_type",
            "OpenVDB grid value types other than float and vec3s",
            "Volume",
            &["volume.create", "volume.update"],
            "Only float and vec3s values are decoded; vec3s density sampling uses magnitude.",
        ),
        unsupported(
            "volume.openvdb_evaluation.compression",
            "OpenVDB compression methods outside raw, zip, and Blosc",
            "Volume",
            &["volume.create", "volume.update"],
            "Raw, zlib/ZIP, and Blosc LZ4/LZ4HC, zlib, and zstd compression are decoded.",
        ),
        unsupported(
            "volume.openvdb_evaluation.blosc_codec",
            "Blosc codecs other than LZ4/LZ4HC, zlib, and zstd",
            "Volume",
            &["volume.create", "volume.update"],
            "BloscLZ and Snappy codecs are not decoded; Blender 5.2.2 output uses the LZ4-compatible codec format.",
        ),
        unsupported(
            "volume.openvdb_evaluation.blosc_bitshuffle",
            "Blosc bit-shuffled value blocks",
            "Volume",
            &["volume.create", "volume.update"],
            "Byte-shuffled Blosc data is decoded; bitshuffle is not.",
        ),
        unsupported(
            "volume.openvdb_evaluation.blosc_version",
            "Blosc formats outside the supported version pair",
            "Volume",
            &["volume.create", "volume.update"],
            "Blosc format versions 1 and 2 with codec format version 1 are decoded.",
        ),
        unsupported(
            "volume.openvdb_evaluation.blosc_flags",
            "Reserved Blosc container flags",
            "Volume",
            &["volume.create", "volume.update"],
            "Reserved Blosc flag bit 3 is rejected.",
        ),
        unsupported(
            "volume.openvdb_evaluation.tree_buffers",
            "Nonstandard OpenVDB tree configurations and multi-buffer trees",
            "Volume",
            &["volume.create", "volume.update"],
            "Only standard 5-4-3 trees with a single leaf buffer are decoded.",
        ),
        unsupported(
            "volume.openvdb_evaluation.resource_budget",
            "OpenVDB archives exceeding volume resource budgets",
            "Volume",
            &["volume.create", "volume.update"],
            "Input archives are capped at 1 GiB and decoded tree data at one million voxels.",
        ),
        unsupported(
            "volume.external_blob_samples",
            "External volume sample blobs without decoded f32 values",
            "Volume",
            &["volume.create", "volume.update"],
            "External sample references are preserved, but evaluation requires decoded inline values or a decoded f32 blob.",
        ),
        unsupported(
            "volume.file_format",
            "Non-VDB external volume file formats",
            "Volume",
            &["volume.create", "volume.update"],
            "VDB file sources are decoded; other external volume formats are retained as metadata only.",
        ),
        supported(
            "curve.spline_geometry",
            "Bezier, polyline, and rational NURBS splines with bevel and simple 2D fill",
            "Curve",
            &[
                "curve.create",
                "curve.update",
                "curve.point_add",
                "curve.point_update",
                "curve.point_delete",
                "curve.convert",
            ],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "surface.nurbs",
            "Rectangular rational NURBS surface grids",
            "Surface",
            &["surface.create"],
            [true, false, true, true, false, false, false],
        ),
        supported(
            "text.hershey_simplex",
            "Built-in Hershey Simplex vector text with alignment and extrusion",
            "Text",
            &["text_object.create", "text_object.update"],
            [true, true, true, true, false, false, false],
        ),
        unsupported(
            "text.font.external",
            "External text font files",
            "Text",
            &["text_object.create", "text_object.update"],
            "Only the built-in public-domain Hershey Simplex font is included.",
        ),
        supported(
            "hair_curves.lines",
            "Hair curves evaluated as loose line paths",
            "Hair Curves",
            &[],
            [false, false, true, true, true, false, true],
        ),
        unsupported(
            "curve.taper_object",
            "Curve taper objects",
            "Curve",
            &["curve.create", "curve.update"],
            "Taper profiles reference another curve Data-Block and are not evaluated.",
        ),
        unsupported(
            "curve.convert.destination",
            "Non-mesh curve conversion destinations",
            "Curve",
            &["curve.convert"],
            "Curve conversion currently supports explicit conversion to mesh only.",
        ),
        unsupported(
            "curve.fill.multiple_contours",
            "Multi-contour 2D curve fills",
            "Curve",
            &["curve.create", "curve.update"],
            "2D fill evaluation supports one simple closed contour and cannot combine holes or separate filled contours.",
        ),
        supported(
            "mesh.element_edit",
            "Mesh editing operations",
            "Mesh",
            &[
                "mesh.transform_elements",
                "mesh.extrude",
                "mesh.inset",
                "mesh.bevel",
                "mesh.subdivide",
                "mesh.triangulate",
                "mesh.poke",
                "mesh.delete",
                "mesh.dissolve",
                "mesh.weld",
                "mesh.fill",
                "mesh.bisect",
                "mesh.mirror",
                "mesh.flip_normals",
                "mesh.set_attribute",
                "mesh.edge_slide",
                "mesh.vertex_slide",
                "mesh.spin",
                "mesh.screw",
                "mesh.merge",
                "mesh.rip",
                "mesh.shade_smooth",
                "mesh.shade_flat",
                "mesh.auto_smooth",
                "mesh.mark_sharp_by_angle",
                "mesh.set_custom_normals",
                "mesh.loop_cut",
                "mesh.bridge",
                "mesh.split",
                "mesh.knife",
                "mesh.remesh",
                "mesh.symmetrize",
                "mesh.separate",
            ],
            [false, true, true, true, false, false, false],
        ),
        supported(
            "mesh.editing",
            "Mesh editing tools and explicit element selectors",
            "Mesh",
            &[
                "mesh.transform_elements",
                "mesh.poke",
                "mesh.edge_slide",
                "mesh.vertex_slide",
                "mesh.spin",
                "mesh.screw",
                "mesh.rip",
                "mesh.merge",
                "mesh.separate",
                "node.join",
                "mesh.shade_smooth",
                "mesh.shade_flat",
                "mesh.auto_smooth",
                "mesh.mark_sharp_by_angle",
                "mesh.set_custom_normals",
            ],
            [false, true, true, true, false, false, false],
        ),
        supported(
            "mesh.attributes",
            "Mesh domain attributes",
            "Mesh",
            &[
                "mesh.attribute_create",
                "mesh.attribute_update",
                "mesh.attribute_delete",
            ],
            [false, true, true, true, false, false, false],
        ),
        supported(
            "modifier.authoring",
            "Modifier stack authoring",
            "Modifier",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.delete",
                "modifier.reorder",
                "modifier.bind",
                "modifier.unbind",
                "modifier.apply",
                "modifier.apply_as_shape_key",
            ],
            [true, true, true, false, false, false, false],
        ),
        supported(
            "modifier.mirror",
            "Mirror modifier",
            "MIRROR",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.array",
            "Array modifier",
            "ARRAY",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.subdivision",
            "Subdivision modifier",
            "SUBSURF",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.solidify",
            "Solidify modifier",
            "SOLIDIFY",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.triangulate",
            "Triangulate modifier",
            "TRIANGULATE",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.bevel",
            "Bevel modifier",
            "BEVEL",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "modifier.bevel.high_valence_vertex_mesh",
            "Bevel high-valence vertex meshes",
            "BEVEL",
            &["modifier.create"],
            "Blender 5.2.2 bevels four-or-more-edge vertices with multiple selected edges using a BMesh ADJ vertex mesh that Potter does not reproduce; the stacked gear probe diverged by 2.760223e-2 in vertex position.",
        ),
        supported(
            "modifier.decimate",
            "Decimate modifier",
            "DECIMATE",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "modifier.decimate.collapse_vertex_group_invert",
            "Decimate COLLAPSE inverted vertex-group weights",
            "DECIMATE",
            &["modifier.create"],
            "Blender 5.2.2 COLLAPSE evaluation with an inverted vertex group is not parity-compatible for any ratio below 1.0; the grid ratio-0.7 probe differed by one face/edge and 1.554746e-1 in vertex position.",
        ),
        supported(
            "modifier.weld",
            "Weld modifier",
            "WELD",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.displace",
            "Displace modifier",
            "DISPLACE",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.smooth",
            "Smooth modifier",
            "SMOOTH",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.boolean",
            "Boolean mesh modifier with exact-predicate BSP",
            "BOOLEAN",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "modifier.boolean.downstream_topology",
            "Boolean output followed by a topology-dependent modifier",
            "BOOLEAN",
            &[],
            "The Boolean mesh surface is supported, but its output topology is not Blender-compatible; topology-dependent downstream modifiers can therefore diverge.",
        ),
        supported(
            "modifier.shrinkwrap",
            "Shrinkwrap mesh modifier",
            "SHRINKWRAP",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.cast",
            "Cast modifier",
            "CAST",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.simple_deform",
            "Simple Deform modifier",
            "SIMPLE_DEFORM",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.screw",
            "Screw modifier",
            "SCREW",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.wave",
            "Wave modifier",
            "WAVE",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.mesh_sequence_cache",
            "Alembic Mesh Sequence Cache modifier",
            "MESH_SEQUENCE_CACHE",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.mesh_sequence_cache.velocity_scale",
            "Mesh Sequence Cache velocity scaling",
            "MESH_SEQUENCE_CACHE",
            &["modifier.create"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.warp",
            "Warp modifier",
            "WARP",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.laplacian_smooth",
            "Laplacian Smooth modifier",
            "LAPLACIANSMOOTH",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.corrective_smooth",
            "Corrective Smooth modifier",
            "CORRECTIVE_SMOOTH",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.edge_split",
            "Edge Split modifier",
            "EDGE_SPLIT",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.build",
            "Build modifier",
            "BUILD",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.mask",
            "Vertex-group Mask modifier",
            "MASK",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.wireframe",
            "Wireframe modifier",
            "WIREFRAME",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.curve",
            "Curve deformation modifier",
            "CURVE",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.hook",
            "Hook modifier",
            "HOOK",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.skin",
            "Skin modifier for skeleton meshes",
            "SKIN",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "modifier.skin.branch_hull",
            "Skin modifier branch-hull generation",
            "SKIN",
            &["modifier.create", "modifier.apply"],
            "Branch-node Skin geometry does not yet match Blender's BMesh hull and cleanup behavior.",
        ),
        supported(
            "modifier.vertex_weight_edit",
            "Vertex Weight Edit with curve falloff and constant, group, or image masks",
            "VERTEX_WEIGHT_EDIT",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.vertex_weight_mix",
            "Vertex Weight Mix across Blender weight operations and mix sets",
            "VERTEX_WEIGHT_MIX",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.vertex_weight_proximity",
            "Vertex Weight Proximity using object-origin or mesh-domain distance",
            "VERTEX_WEIGHT_PROXIMITY",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.weighted_normal",
            "Weighted Normal writes custom split normals in the corner domain",
            "WEIGHTED_NORMAL",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.normal_edit",
            "Normal Edit writes radial or directional custom split normals",
            "NORMAL_EDIT",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.uv_project",
            "Camera and object UV projection into named mesh UV layers",
            "UV_PROJECT",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.uv_warp",
            "UV-domain scale, rotation, offset, and object-relative warp",
            "UV_WARP",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.data_transfer",
            "Nearest, topology, and polygon-interpolated mesh-domain attribute transfer",
            "DATA_TRANSFER",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.mesh_cache",
            "PC2 and MDD point caches with scene-time interpolation and axis conversion",
            "MESH_CACHE",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.surface_deform",
            "Bound Surface Deform with adjacent-polygon mean-value weights and normal offsets",
            "SURFACE_DEFORM",
            &[
                "modifier.create",
                "modifier.bind",
                "modifier.unbind",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.mesh_deform",
            "Bound Mesh Deform with voxel-grid harmonic cage coordinates",
            "MESH_DEFORM",
            &[
                "modifier.create",
                "modifier.bind",
                "modifier.unbind",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.laplacian_deform",
            "Bound cotangent Laplacian surface editing with hard vertex-group anchors",
            "LAPLACIANDEFORM",
            &[
                "modifier.create",
                "modifier.bind",
                "modifier.unbind",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.remesh",
            "BLOCKS, SMOOTH, and SHARP dual-contouring plus VOXEL signed-distance remesh with resource-capped grids",
            "REMESH",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "modifier.remesh.voxel_adaptivity",
            "Blender VOXEL remesh with nonzero adaptivity",
            "REMESH",
            &["modifier.create", "modifier.apply"],
            "OpenVDB adaptive volume meshing is not implemented; zero-adaptivity uniform voxel remeshing is supported.",
        ),
        unsupported(
            "modifier.remesh.open_nonmanifold",
            "Blender dual-contouring Remesh with unresolved open-surface ring paths",
            "REMESH",
            &["modifier.create", "modifier.apply"],
            "Open/non-manifold meshes with sign-mask transitions not covered by closed leaf-ring paths remain unsupported; the recursive Blender patchSplit/connectFace repair is not implemented.",
        ),
        supported(
            "modifier.ocean",
            "Seeded Tessendorf FFT ocean with generated and displaced geometry",
            "OCEAN",
            &["modifier.create", "modifier.apply"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.cloth",
            "Frame-cached cloth solver evaluated at its object-stack position",
            "CLOTH",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "physics.cloth.create",
                "physics.cloth.update",
                "physics.cloth.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.soft_body",
            "Frame-cached soft-body solver evaluated at its object-stack position",
            "SOFT_BODY",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "physics.soft_body.create",
                "physics.soft_body.update",
                "physics.soft_body.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.collision",
            "Collision surface participating in native physics evaluation",
            "COLLISION",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "physics.collision.create",
                "physics.collision.update",
                "physics.collision.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.dynamic_paint",
            "Dynamic paint evaluator applying canvas attributes at stack position",
            "DYNAMIC_PAINT",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "physics.dynamic_paint.create",
                "physics.dynamic_paint.update",
                "physics.dynamic_paint.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.fluid",
            "Frame-cached liquid surface evaluator at its object-stack position",
            "FLUID",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "physics.fluid.create",
                "physics.fluid.update",
                "physics.fluid.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.particle_system",
            "Frame-cached particle emitter evaluated from the mesh at its stack position",
            "PARTICLE_SYSTEM",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "physics.particle_emitter.create",
                "physics.particle_emitter.update",
                "physics.particle_emitter.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.particle_instance",
            "Copies evaluated object geometry to evaluated particle transforms",
            "PARTICLE_INSTANCE",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "modifier.particle_instance.use_path",
            "Particle Instance along sampled particle paths",
            "PARTICLE_INSTANCE",
            &[],
            "Blender samples cached particle path trajectories and incrementally transported orientation frames; the current particle-state model stores only birth and current states.",
        ),
        supported(
            "modifier.explode",
            "Splits stack geometry into particle-driven disconnected face fragments",
            "EXPLODE",
            &[
                "modifier.create",
                "modifier.update",
                "modifier.reorder",
                "modifier.apply",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.volume_displace",
            "Resamples inline scalar grids and single-grid VDB density with local, global, or object texture coordinates",
            "VOLUME_DISPLACE",
            &["modifier.create", "modifier.update", "modifier.reorder"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.apply_as_shape_key",
            "Apply a topology-preserving modifier result as a shape key",
            "OBJECT_OT_modifier_apply_as_shapekey",
            &["modifier.apply_as_shape_key"],
            [false, true, true, true, true, false, false],
        ),
        unsupported(
            "modifier.grease_pencil",
            "Grease Pencil and Line Art modifiers",
            "Modifier",
            &[],
            "All Blender mesh, volume, and physics modifier types are modeled; Grease Pencil stroke modifiers (GREASE_PENCIL_*, LINEART) are not.",
        ),
        supported(
            "modifier.armature",
            "Armature modifier with evaluated linear-blend skinning",
            "ARMATURE",
            &["modifier.create", "modifier.update"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "modifier.armature_apply",
            "Apply frame-evaluated armature deformation without shape-key stacks",
            "ARMATURE",
            &["modifier.apply"],
            [false, true, true, true, true, false, false],
        ),
        supported(
            "modifier.apply.shape_key_guard",
            "Blender-equivalent rejection of Apply on mesh shape keys",
            "Modifier",
            &["modifier.apply", "modifier.apply_as_shape_key"],
            [false, true, true, true, true, false, false],
        ),
        unsupported(
            "geometry_nodes",
            "Other Geometry Nodes evaluation",
            "GeometryNodeTree",
            &[],
            "Curve, volume, material, and other node families beyond the native mesh evaluator are not implemented; persistent simulation baking and non-geometry state items are also unsupported.",
        ),
        supported(
            "geometry_nodes.evaluator_subset",
            "Mesh primitives, geometry editing, point distribution, field math, attributes, repeat zones, and frame-cached simulation zones",
            "GeometryNodeTree",
            &[
                "graph.create",
                "graph.delete",
                "graph.node_add",
                "graph.node_update",
                "graph.node_remove",
                "graph.link",
                "graph.unlink",
                "graph.interface_update",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "sculpt.advanced",
            "Advanced sculpt brushes and dynamic topology",
            "Sculpt",
            &["sculpt.stroke", "sculpt.dyntopo"],
            [false, true, true, true, true, false, false],
        ),
        unsupported(
            "sculpt.layers",
            "Non-destructive sculpt layer stacks",
            "Sculpt",
            &[],
            "Sculpt layer stacks with persistent per-layer displacement and blend controls are not implemented; the layer brush remains a direct stroke.",
        ),
        supported(
            "sculpt.mesh_operations",
            "Sculpt strokes, masks, face sets, voxel remesh, and multiresolution",
            "Mesh",
            &[
                "sculpt.stroke",
                "sculpt.mask",
                "sculpt.face_set",
                "sculpt.remesh_voxel",
                "sculpt.multires",
            ],
            [false, true, true, true, true, false, false],
        ),
        supported(
            "image.datablocks",
            "Generated, packed, linked images, and UDIM pixel tiles",
            "Image",
            &[
                "image.create",
                "image.delete",
                "image.load",
                "image.set_pixels",
                "image.update",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "image.encoding.non_png",
            "JPEG, TIFF, OpenEXR, WebP, BMP, TGA, and Radiance HDR image loading",
            "Image",
            &["image.load"],
            [false, true, true, true, true, true, false],
        ),
        supported(
            "paint.texture",
            "UV-mapped texture painting",
            "Paint",
            &["paint.texture"],
            [false, true, true, true, true, false, false],
        ),
        supported(
            "paint.vertex",
            "Vertex paint",
            "Mesh",
            &["paint.vertex"],
            [false, true, true, true, true, false, false],
        ),
        supported(
            "paint.weight",
            "Vertex-group weight painting",
            "Mesh",
            &["paint.weight"],
            [false, true, true, true, true, false, false],
        ),
        unsupported(
            "uv",
            "Complete Blender UV workflow",
            "UVMap",
            &["uv.unwrap", "uv.transform", "uv.pin", "uv.pack"],
            "The implementation now supports projected, angle-based, and conformal seam-aware unwraps with pin constraints, but does not implement the complete Blender UV workflow.",
        ),
        supported(
            "uv.projected_mapping",
            "Box, smart, and cube face UV projection",
            "UVMap",
            &["uv.unwrap"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "uv.advanced_unwrap",
            "Angle-based and conformal seam-aware unwrap with pins",
            "UVMap",
            &["uv.unwrap"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "uv.transform",
            "UV face transforms",
            "UVMap",
            &["uv.transform"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "uv.pin",
            "UV face pinning",
            "UVMap",
            &["uv.pin"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "uv.pack",
            "UV island packing",
            "UVMap",
            &["uv.pack"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "animation.action_authoring",
            "Action authoring",
            "Action",
            &["action.create", "action.update", "action.delete"],
            [true, true, true, false, false, false, false],
        ),
        supported(
            "animation.keyframe_authoring",
            "Transform keyframe editing",
            "Keyframe",
            &["keyframe.insert", "keyframe.delete"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "animation.fcurve_extrapolation",
            "F-Curve extrapolation",
            "FCurve",
            &["fcurve.update"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "animation.transform_evaluation",
            "Supported transform Action curves",
            "Action",
            &["action.update", "keyframe.insert"],
            [false, false, true, true, true, false, false],
        ),
        supported(
            "animation.nla",
            "Basic Action slots, NLA transform blending, and timeline markers",
            "Action/NLA",
            &[
                "action.slot_create",
                "nla.track_create",
                "nla.track_update",
                "nla.track_delete",
                "nla.strip_create",
                "nla.strip_update",
                "nla.strip_delete",
                "nla.push_down",
                "scene.marker_add",
                "scene.marker_remove",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "animation.keyframe",
            "Advanced keyframe and NLA controls",
            "Keyframe",
            &[],
            "Bezier handle editing and Blender-specific retiming/blend semantics are not implemented.",
        ),
        unsupported(
            "animation.fcurve",
            "Full Blender F-Curve feature set",
            "FCurve",
            &[],
            "Curve modifiers and non-transform channels beyond the supported Action and driver subsets are not implemented.",
        ),
        supported(
            "rig.advanced",
            "Advanced rigging, absolute shape keys, and difference drivers",
            "Armature/Key/Driver",
            &[
                "bone.create",
                "bone.update",
                "bone_collection.create",
                "bone_collection.update",
                "bone_collection.delete",
                "bone_collection.assign",
                "bone_collection.unassign",
                "modifier.create",
                "modifier.update",
                "shape_key.create",
                "shape_key.update",
                "shape_key.delete",
                "action.create",
                "action.update",
                "keyframe.insert",
                "keyframe.delete",
                "driver.create",
                "driver.update",
                "driver.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "rig.bone_collections_shapes_envelopes",
            "Bone collections, custom bone shapes, and envelope deformation",
            "Armature",
            &[
                "bone.create",
                "bone.update",
                "bone_collection.create",
                "bone_collection.update",
                "bone_collection.delete",
                "bone_collection.assign",
                "bone_collection.unassign",
                "modifier.create",
                "modifier.update",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "rig.rigify",
            "Rigify-lite fixed basic-human rig generation",
            "Armature",
            &["rig.generate_basic_human"],
            [true, false, true, true, false, false, false],
        ),
        unsupported(
            "rig.rigify.full",
            "Full Blender Rigify metarig generation and metadata",
            "Armature",
            &[],
            "Only a fixed, scale-adjustable basic-human template is available through rig.generate_basic_human; Blender Rigify metarig-based generation, selectable rig types, generator options, and Rigify-specific metadata are not implemented.",
        ),
        supported(
            "rig.bones_pose",
            "Editable rest bones and pose transforms",
            "Armature",
            &[
                "bone.create",
                "bone.update",
                "bone.delete",
                "pose.set",
                "pose.reset",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "constraint.transform_subset",
            "Copy, limit, tracking, child-of, and IK constraints",
            "Constraint",
            &[
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "constraint.ik.swing_ellipse_limit",
            "Legacy IK X/Z Swing ellipse limits",
            "IK",
            &[],
            "Strict Blender parity for simultaneous X/Z Swing ellipse limits with lock re-solves is not reliable across stretch and pole-influence combinations.",
        ),
        supported(
            "constraint.extended_transform",
            "Locked track, stretch-to, transformation, maintain-volume, floor, pivot, and shrinkwrap-lite constraints",
            "Constraint",
            &[
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "constraint.spline_ik.poly_bezier",
            "Spline IK for poly and Bezier curves",
            "SPLINE_IK",
            &[
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "constraint.spline_ik.nurbs",
            "Spline IK for rational NURBS curves",
            "SPLINE_IK",
            &[
                "curve.create",
                "curve.update",
                "curve.point_add",
                "curve.point_update",
                "curve.point_delete",
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "constraint.spline_ik.multiple_splines",
            "Spline IK selecting a spline from a multi-spline curve",
            "SPLINE_IK",
            &[
                "curve.create",
                "curve.update",
                "curve.point_add",
                "curve.point_update",
                "curve.point_delete",
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "constraint.transform_cache",
            "Alembic Transform Cache object constraint",
            "TRANSFORM_CACHE",
            &[
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "constraint.transform_cache.pose_bone",
            "Alembic Transform Cache pose-bone constraint",
            "TRANSFORM_CACHE",
            &[
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "constraint.transform_cache.usd",
            "USD Transform Cache archives",
            "TRANSFORM_CACHE",
            &[],
            "USD, USDC, and USDZ transform-cache sampling is not implemented; only Alembic Xforms are evaluated.",
        ),
        supported(
            "constraint.action",
            "Action-driven transform constraint",
            "ACTION",
            &[
                "action.create",
                "action.update",
                "keyframe.insert",
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "constraint.action.target_space",
            "Action constraint custom target-space corrections",
            "ACTION",
            &[],
            "CUSTOM and LOCAL_OWNER_ORIENT target-space corrections require custom-space and rest-bone orientation inputs that are not modeled.",
        ),
        supported(
            "constraint.geometry_attribute",
            "Geometry Attribute constraint",
            "GEOMETRY_ATTRIBUTE",
            &[
                "mesh.attribute_create",
                "mesh.attribute_update",
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "constraint.geometry_attribute.instances",
            "Geometry Attribute INSTANCE-domain sampling",
            "GEOMETRY_ATTRIBUTE",
            &[],
            "Evaluated geometry instances are not exposed by the current constraint evaluator.",
        ),
        unsupported(
            "constraint.geometry_attribute.curve_domain",
            "Geometry Attribute CURVE-domain sampling",
            "GEOMETRY_ATTRIBUTE",
            &[],
            "The constraint target model currently samples mesh domains, not curve components.",
        ),
        supported(
            "constraint.camera_solver",
            "Camera reconstruction solver constraint",
            "CAMERA_SOLVER",
            &[
                "tracking.solve_camera",
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "constraint.follow_track",
            "Movie tracking marker follow constraint",
            "FOLLOW_TRACK",
            &[
                "tracking.track_add",
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "constraint.follow_track.depth_object_mesh",
            "Follow Track depth objects without mesh data",
            "FOLLOW_TRACK",
            &[],
            "Depth-object ray casting is defined only for mesh data.",
        ),
        unsupported(
            "constraint.follow_track.depth_object_modifiers",
            "Follow Track depth objects with modifiers",
            "FOLLOW_TRACK",
            &[],
            "Depth-object ray casting currently reads base mesh data rather than evaluated modifier output.",
        ),
        supported(
            "constraint.object_solver",
            "Tracked object reconstruction solver constraint",
            "OBJECT_SOLVER",
            &[
                "tracking.solve_object",
                "constraint.create",
                "constraint.update",
                "constraint.delete",
                "constraint.reorder",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "constraint.other_standard",
            "Other standard Blender constraints",
            "Constraint",
            &[],
            "Remaining Blender standard constraint types outside the supported transform, Transform Cache, spline IK, Action, Geometry Attribute, Camera Solver, Follow Track, and Object Solver subsets are not implemented.",
        ),
        unsupported(
            "constraint.target_bbone_shape",
            "Constraint targets sampled along segmented B-Bone shapes",
            "Constraint",
            &[],
            "Sampling a target pose bone along its curved B-Bone segments requires Blender's evaluated B-Bone pose matrices.",
        ),
        supported(
            "driver.safe_expression",
            "Safe arithmetic property drivers",
            "Driver",
            &["driver.create", "driver.update", "driver.delete"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "driver.location_rotation_difference",
            "Location and rotation difference driver variables",
            "DriverVariable",
            &["driver.create", "driver.update", "driver.delete"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "shape_key.deformation",
            "Relative shape-key storage and evaluation",
            "Key",
            &["shape_key.create", "shape_key.update", "shape_key.delete"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "shape_key.absolute",
            "Absolute shape keys and evaluation-time interpolation",
            "Key",
            &[
                "shape_key.create",
                "shape_key.update",
                "shape_key.delete",
                "node.update",
                "action.create",
                "action.update",
                "keyframe.insert",
                "keyframe.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "rig.vertex_groups",
            "Vertex groups and linear-blend skinning",
            "VertexGroup",
            &[
                "vertex_group.create",
                "vertex_group.assign",
                "vertex_group.remove",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "rig.bbone.segments",
            "Armature deformation through B-Bone segments",
            "Armature",
            &[],
            "Armature modifiers and Armature constraints deform vertices along curved B-Bone segments, which are not evaluated.",
        ),
        supported(
            "physics.world",
            "Rigid-body world settings",
            "RigidBodyWorld",
            &["physics.world.update", "simulation.settings.update"],
            [false, true, true, true, false, false, false],
        ),
        supported(
            "physics.rigid_body",
            "Active and passive box, sphere, convex-hull, and mesh bodies",
            "RigidBody",
            &[
                "physics.rigid_body.create",
                "physics.rigid_body.update",
                "physics.rigid_body.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "physics.force_field",
            "Wind, vortex, and force fields",
            "Field",
            &[
                "physics.force_field.create",
                "physics.force_field.update",
                "physics.force_field.delete",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "simulation.rigid_body_bake",
            "Deterministic cached physics simulation and per-frame bake",
            "Simulation",
            &["simulation.settings.update"],
            [false, false, true, true, true, false, true],
        ),
        supported(
            "physics.cloth",
            "Deterministic mass-spring cloth simulation with pinned vertex groups",
            "Cloth",
            &[
                "physics.cloth.create",
                "physics.cloth.update",
                "physics.cloth.delete",
            ],
            [true, true, true, true, true, false, true],
        ),
        unsupported(
            "physics.cloth.blender_solver_parity",
            "Blender implicit cloth-solver numerical parity",
            "Cloth",
            &[],
            "Potter uses deterministic XPBD distance constraints rather than Blender's implicit cloth solver, so later-frame per-vertex trajectories are not numerically equivalent.",
        ),
        supported(
            "physics.soft_body",
            "Deterministic XPBD soft-body simulation with goal weights and volume constraints",
            "SoftBody",
            &[
                "physics.soft_body.create",
                "physics.soft_body.update",
                "physics.soft_body.delete",
            ],
            [true, true, true, true, true, false, true],
        ),
        supported(
            "physics.particle_emitter",
            "Seeded particle emission with face or vertex sampling and cached trajectories",
            "ParticleSystem",
            &[
                "physics.particle_emitter.create",
                "physics.particle_emitter.update",
                "physics.particle_emitter.delete",
            ],
            [true, true, true, true, true, false, true],
        ),
        supported(
            "physics.fluid",
            "SPH liquid simulation with an evaluated metaball surface",
            "FluidDomain",
            &[
                "physics.fluid.create",
                "physics.fluid.update",
                "physics.fluid.delete",
            ],
            [true, true, true, true, true, false, true],
        ),
        supported(
            "physics.dynamic_paint",
            "Brush-proximity dynamic-paint vertex color or weight canvas",
            "DynamicPaint",
            &[
                "physics.dynamic_paint.create",
                "physics.dynamic_paint.update",
                "physics.dynamic_paint.delete",
            ],
            [true, true, true, true, false, false, true],
        ),
        unsupported(
            "physics.fluid.smoke_fire",
            "Smoke and fire fluids",
            "FluidDomain",
            &[],
            "Only liquid SPH simulation is supported; Eulerian smoke and fire simulation are not implemented.",
        ),
        unsupported(
            "physics",
            "Other Blender physics systems",
            "Physics",
            &[],
            "Simulation nodes and physics systems outside the supported rigid body, force field, cloth, soft body, particle, liquid, and dynamic paint subset are not supported.",
        ),
        supported(
            "grease_pencil.strokes",
            "Grease Pencil layers, frames, strokes, and evaluated line preview",
            "GreasePencil",
            &[
                "grease_pencil.layer_create",
                "grease_pencil.layer_update",
                "grease_pencil.layer_delete",
                "grease_pencil.frame_add",
                "grease_pencil.stroke_add",
                "grease_pencil.stroke_update",
                "grease_pencil.stroke_delete",
            ],
            [true, true, true, true, true, false, true],
        ),
        unsupported(
            "grease_pencil.advanced",
            "Advanced Grease Pencil features",
            "GreasePencil",
            &[],
            "Fill geometry, effects, and Blender-specific Grease Pencil modifiers are not implemented.",
        ),
        supported(
            "camera.data",
            "Perspective, orthographic, panorama, and fisheye camera data",
            "Camera",
            &["camera.create", "camera.update"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "camera.shift",
            "Lens shift for perspective and orthographic cameras",
            "Camera",
            &["camera.create", "camera.update"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "camera.panorama",
            "Equirectangular and equidistant fisheye projections",
            "Camera",
            &["camera.create", "camera.update"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "camera.stereo",
            "Side-by-side and anaglyph stereo views",
            "Camera",
            &["camera.create", "camera.update"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "camera.dof",
            "Depth of field with focus distance, f-stop, and aperture blades",
            "Camera",
            &["camera.create", "camera.update"],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "light.data",
            "Point, sun, spot, and area light data",
            "Light",
            &["light.create", "light.update"],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "world.parameters",
            "World color and strength parameters",
            "World",
            &["world.create", "world.update"],
            [true, true, true, false, false, false, false],
        ),
        supported(
            "world",
            "World node graphs with analytic sky and equirectangular environment lighting",
            "World",
            &[
                "world.create",
                "world.update",
                "graph.create",
                "graph.node_add",
                "graph.link",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "render.preview",
            "CPU preview modes: solid, beauty, wire, normal, depth, and ID",
            "Render",
            &[],
            [false, false, true, true, true, false, true],
        ),
        supported(
            "render.settings",
            "Scene render output settings",
            "Scene Render",
            &["render.update"],
            [false, true, true, false, false, false, false],
        ),
        supported(
            "render.passes",
            "Combined, depth, normal, albedo, emission, object index, Cryptomatte-lite, and AO render passes",
            "Render",
            &["render.passes_update"],
            [false, true, true, true, true, false, false],
        ),
        supported(
            "render.pass.ao",
            "Finite-radius BVH hemisphere ambient-occlusion visibility",
            "Render Pass",
            &["render.passes_update"],
            [false, true, true, true, true, false, false],
        ),
        supported(
            "render.multilayer_exr",
            "Selected render passes written as named multilayer OpenEXR layers",
            "OpenEXR",
            &["render.passes_update"],
            [false, false, true, true, true, false, false],
        ),
        supported(
            "render.path",
            "CPU Principled-lite path tracing",
            "Render",
            &[],
            [false, false, true, true, true, false, false],
        ),
        supported(
            "render.motion_blur",
            "Deterministic shutter-sampled subframe motion blur",
            "Render",
            &["render.update"],
            [false, true, true, false, true, false, false],
        ),
        supported(
            "render.realtime",
            "Deterministic CPU realtime raster with GGX lighting, point/spot cubemap shadow maps with 3x3 PCF, BVH-filtered sun/area shadows, ambient occlusion, and alpha blend/clip",
            "Render",
            &[],
            [false, false, true, true, true, false, false],
        ),
        supported(
            "compositor",
            "Compositor graph and CPU node evaluation",
            "CompositorNodeTree",
            &[
                "graph.create",
                "graph.delete",
                "compositor.enable",
                "compositor.node_add",
                "compositor.node_update",
                "compositor.node_remove",
                "compositor.link",
            ],
            [true, true, true, true, true, false, false],
        ),
        supported(
            "color_management",
            "Standard, AgX, Filmic, Raw, and False Color scene display transforms",
            "ColorManagement",
            &["color.update"],
            [false, true, true, true, true, false, false],
        ),
        unsupported(
            "color_management.ocio",
            "Arbitrary OpenColorIO configurations, displays, and views",
            "ColorManagement",
            &[],
            "The renderer supports fixed built-in transforms and sRGB display encoding, not arbitrary OCIO profiles.",
        ),
        supported(
            "tracking",
            "2D and plane tracking, camera and tracked-object reconstruction, intrinsics, and lens correction",
            "MovieClip",
            &[
                "tracking.clip_create",
                "tracking.track_add",
                "tracking.track",
                "tracking.plane_track",
                "tracking.solve_camera",
                "tracking.solve_object",
                "tracking.set_camera_intrinsics",
                "tracking.undistort",
            ],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "tracking.object_solve",
            "Tracked object-motion reconstruction",
            "MovieTrackingObject",
            &[
                "tracking.clip_create",
                "tracking.track_add",
                "tracking.solve_camera",
                "tracking.solve_object",
            ],
            [true, true, true, true, false, false, false],
        ),
        supported(
            "mask",
            "Polygon masks",
            "Mask",
            &["mask.create", "mask.update", "mask.delete"],
            [true, true, true, false, false, false, false],
        ),
        unsupported(
            "mask.bezier_spline",
            "Bezier mask spline handles",
            "MaskSpline",
            &[],
            "Mask contours currently use polygonal line segments rather than Bezier handles.",
        ),
        supported(
            "sequencer",
            "Image, scene, sound, meta, transition, and effect strips with retiming and audio mixdown",
            "Sequence",
            &[
                "sequencer.strip_create",
                "sequencer.strip_update",
                "sequencer.strip_delete",
                "sequencer.update",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "sequencer.strip.movie",
            "Movie strip decoding",
            "Sequence",
            &[],
            "Movie strips cannot be rendered because no pure-Rust movie decoder is available.",
        ),
        unsupported(
            "sequencer.strip.text.unicode",
            "Unicode text strip rendering",
            "Sequence",
            &[],
            "The built-in text strip rasterizer supports ASCII glyphs only.",
        ),
        supported(
            "asset.library",
            "Native Potter project and Blender libraries with linked IDs, editable overrides, reload, and relocation",
            "Library",
            &[
                "library.link",
                "library.append",
                "library.override",
                "library.register",
                "library.reload",
                "library.relocate",
            ],
            [true, true, true, true, true, false, false],
        ),
        unsupported(
            "asset.library.other_registries",
            "Other linked library registries",
            "Library",
            &["library.link"],
            "Linking scenes, movie clips, and masks is not implemented.",
        ),
        supported(
            "asset.resource_pack",
            "Pack and unpack byte-backed resources",
            "Resource",
            &["resource.pack", "resource.unpack"],
            [true, true, true, false, false, false, false],
        ),
        unsupported(
            "asset.resource_resolution",
            "External resource retrieval",
            "Resource",
            &[],
            "Remote resource resolution and dependency acquisition are not implemented.",
        ),
        supported(
            "asset.metadata",
            "Asset metadata and catalogs",
            "Asset",
            &[
                "asset.mark",
                "asset.clear",
                "asset.update",
                "asset.catalog_create",
            ],
            [true, true, true, false, false, false, false],
        ),
        supported(
            "data.custom_properties",
            "Typed custom properties with subtype and numeric bounds",
            "Custom Property",
            &["property.set", "property.delete"],
            [true, true, true, false, false, false, false],
        ),
        supported(
            "script.text",
            "Source text Data-Blocks",
            "Text",
            &["text.create", "text.update", "text.delete"],
            [true, true, true, false, false, false, false],
        ),
        supported(
            "script.extension_declaration",
            "Declared extension dependencies and permissions",
            "Extension",
            &["extension.register"],
            [true, true, true, false, false, false, false],
        ),
        unsupported(
            "script.execution",
            "Text and extension execution",
            "Extension",
            &[],
            "Scripts and native extension adapters are never executed.",
        ),
    ];
    json!({"catalog_version":1,"features":rows})
}

fn supported(
    feature_id: &str,
    name: &str,
    blender_type: &str,
    pot_ops: &[&str],
    flags: [bool; 7],
) -> Value {
    let ops_present = pot_ops.iter().all(|op| ops::OP_NAMES.contains(op));
    let (status, reason, flags) = if ops_present {
        ("supported", Value::Null, flags)
    } else {
        (
            "not_supported",
            json!("A required typed operation is not implemented."),
            [false; 7],
        )
    };
    feature_row(
        feature_id,
        name,
        blender_type,
        pot_ops,
        flags,
        status,
        &reason,
    )
}

fn unsupported(
    feature_id: &str,
    name: &str,
    blender_type: &str,
    pot_ops: &[&str],
    reason: &str,
) -> Value {
    feature_row(
        feature_id,
        name,
        blender_type,
        pot_ops,
        [false; 7],
        "not_supported",
        &json!(reason),
    )
}

fn feature_row(
    feature_id: &str,
    name: &str,
    blender_type: &str,
    pot_ops: &[&str],
    flags: [bool; 7],
    status: &str,
    reason: &Value,
) -> Value {
    json!({"feature_id":feature_id,"name":name,"blender_type":blender_type,"pot_ops":pot_ops,"capabilities":{"create":flags[0],"edit":flags[1],"inspect":flags[2],"evaluate":flags[3],"render":flags[4],"import":flags[5],"export":flags[6]},"status":status,"reason":reason})
}

#[must_use]
pub fn formats_catalog() -> Value {
    let formats = [
        format_row(
            "blend",
            [true, true],
            &[
                "scene",
                "objects",
                "mesh",
                "simple materials",
                "camera",
                "light",
                "supported modifiers",
                "basic animation",
            ],
            true,
            &["Blender 5.2-compatible headless executable"],
            &[
                "Primitive mesh descriptors, node groups, resources, libraries, world node graphs, constraints, drivers, unsupported object/data-block types, unsupported modifiers, and custom mesh attributes are reported as losses.",
            ],
        ),
        format_row(
            "glb",
            [true, true],
            &[
                "evaluated mesh",
                "basic material",
                "camera",
                "light",
                "metadata",
            ],
            false,
            &[],
            &[
                "Only the adapter's implemented GLTF feature subset is supported; unsupported source features are rejected or reported as losses.",
            ],
        ),
        format_row(
            "gltf",
            [true, true],
            &[
                "evaluated mesh",
                "basic material",
                "camera",
                "light",
                "metadata",
                "sidecar binary",
            ],
            false,
            &[],
            &[
                "Only the adapter's implemented GLTF feature subset is supported; unsupported source features are rejected or reported as losses.",
            ],
        ),
        format_row(
            "obj",
            [true, true],
            &["mesh geometry", "basic material sidecar"],
            false,
            &[],
            &[
                "Scene graph, materials beyond a basic approximation, animation, and production graph are not represented.",
            ],
        ),
        format_row(
            "stl",
            [true, true],
            &["triangulated mesh geometry"],
            false,
            &[],
            &["Materials, transforms, animation, and production graph are not represented."],
        ),
        format_row(
            "ply",
            [true, true],
            &[
                "mesh geometry",
                "vertex normals",
                "vertex colors where present",
            ],
            false,
            &[],
            &["Materials, transforms, animation, and production graph are not represented."],
        ),
        format_row(
            "usda",
            [true, true],
            &[
                "USD ASCII stage",
                "Xform hierarchy",
                "PolyMesh geometry",
                "transform animation",
            ],
            false,
            &[],
            &[
                "Only the implemented USD schema subset is supported; unsupported prim schemas are rejected.",
            ],
        ),
        format_row(
            "usdc",
            [true, true],
            &[
                "USD crate stage",
                "Xform hierarchy",
                "PolyMesh geometry",
                "transform animation",
            ],
            false,
            &[],
            &[
                "Only the implemented USD schema subset is supported; unsupported prim schemas are rejected.",
            ],
        ),
        format_row(
            "usd",
            [true, true],
            &[
                "USD crate stage",
                "Xform hierarchy",
                "PolyMesh geometry",
                "transform animation",
            ],
            false,
            &[],
            &[
                "The `.usd` variant uses the supported USD crate adapter; unsupported prim schemas are rejected.",
            ],
        ),
        format_row(
            "usdz",
            [true, true],
            &[
                "USDZ root-layer package",
                "Xform hierarchy",
                "PolyMesh geometry",
            ],
            false,
            &[],
            &[
                "Only the root USDA layer is handled; embedded assets and unsupported ZIP encodings are not preserved.",
            ],
        ),
        format_row(
            "alembic",
            [true, true],
            &[
                "Xform hierarchy",
                "PolyMesh geometry",
                "normal and UV geom parameters",
                "transform animation",
            ],
            false,
            &[],
            &[
                "Only mesh/empty geometry and transforms are exported; cameras, lights, visibility/selectability, parent-inverse actions, simulation settings, materials, custom node metadata, and unsupported Alembic schemas are reported as losses.",
            ],
        ),
        format_row(
            "fbx",
            [true, true],
            &[
                "scene hierarchy",
                "mesh geometry",
                "materials",
                "armature and animation subset",
            ],
            false,
            &[],
            &[
                "Only the implemented ASCII FBX feature subset is supported; unsupported features are rejected or reported as losses.",
            ],
        ),
        format_row(
            "fbx-binary",
            [true, true],
            &[
                "binary FBX 7.4",
                "scene hierarchy",
                "mesh geometry",
                "materials",
                "armature and animation subset",
            ],
            false,
            &[],
            &[
                "Only the implemented binary FBX 7.4/7.5 feature subset is supported; unsupported features are rejected or reported as losses.",
            ],
        ),
        format_row(
            "bvh",
            [true, true],
            &["armature hierarchy", "rest bones", "pose motion"],
            false,
            &[],
            &["Meshes, materials, and non-armature scene data are not represented."],
        ),
        format_row(
            "svg",
            [true, true],
            &["projected Grease Pencil strokes", "mesh wire projection"],
            false,
            &[],
            &[
                "Only the selected-frame vector projection is preserved; scene graph, materials, fills, and animation are not represented.",
                "SVG paths and polylines using supported M/L/C/Z commands are imported; unsupported SVG constructs are rejected.",
            ],
        ),
        format_row(
            "pdf",
            [false, true],
            &[
                "selected-frame Grease Pencil strokes",
                "mesh wire projection",
            ],
            false,
            &[],
            &[
                "PDF export emits one vector page for the selected frame; import is not supported.",
                "Scene graph, material graph, fills, and animation are not represented.",
            ],
        ),
    ];
    json!({"catalog_version":1,"formats":formats})
}

fn format_row(
    name: &str,
    direction: [bool; 2],
    features: &[&str],
    requires_blender: bool,
    runtime: &[&str],
    loss_conditions: &[&str],
) -> Value {
    let (status, reason) = match name {
        "blend" | "glb" | "gltf" | "usda" | "usdc" | "usd" | "usdz" | "alembic" | "fbx"
        | "fbx-binary" | "bvh" | "obj" | "stl" | "ply" | "svg" | "pdf" => {
            ("supported", Value::Null)
        }
        _ => ("not_supported", json!("Format adapter is not implemented.")),
    };
    json!({"format":name,"direction":{"import":direction[0],"export":direction[1]},"features":features,"required_runtime":runtime,"requires_blender":requires_blender,"loss_conditions":loss_conditions,"status":status,"reason":reason})
}

#[must_use]
pub fn capabilities_schema() -> Value {
    json!({"$schema":"https://json-schema.org/draft/2020-12/schema","title":"Potter capabilities catalog","type":"object","required":["catalog_version","features"],"properties":{"catalog_version":{"const":1},"features":{"type":"array","items":{"$ref":"#/$defs/feature"}}},"$defs":{"feature":{"type":"object","required":["feature_id","name","blender_type","pot_ops","capabilities","status","reason"],"properties":{"feature_id":{"type":"string"},"name":{"type":"string"},"blender_type":{"type":"string"},"pot_ops":{"type":"array","items":{"type":"string"}},"capabilities":{"type":"object","required":["create","edit","inspect","evaluate","render","import","export"],"properties":{"create":{"type":"boolean"},"edit":{"type":"boolean"},"inspect":{"type":"boolean"},"evaluate":{"type":"boolean"},"render":{"type":"boolean"},"import":{"type":"boolean"},"export":{"type":"boolean"}},"additionalProperties":false},"status":{"enum":["supported","not_supported"]},"reason":{"type":["string","null"]}},"additionalProperties":false}}})
}

#[must_use]
pub fn formats_schema() -> Value {
    json!({"$schema":"https://json-schema.org/draft/2020-12/schema","title":"Potter format catalog","type":"object","required":["catalog_version","formats"],"properties":{"catalog_version":{"const":1},"formats":{"type":"array","items":{"$ref":"#/$defs/format"}}},"$defs":{"format":{"type":"object","required":["format","direction","features","required_runtime","requires_blender","loss_conditions","status","reason"],"properties":{"format":{"type":"string"},"direction":{"type":"object","required":["import","export"],"properties":{"import":{"type":"boolean"},"export":{"type":"boolean"}},"additionalProperties":false},"features":{"type":"array","items":{"type":"string"}},"required_runtime":{"type":"array","items":{"type":"string"}},"requires_blender":{"type":"boolean"},"loss_conditions":{"type":"array","items":{"type":"string"}},"status":{"enum":["supported","not_supported"]},"reason":{"type":["string","null"]}},"additionalProperties":false}}})
}
